CREATE TABLE SUPPLIER (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NAME NVARCHAR2(200) NOT NULL,
EMAIL NVARCHAR2(150) NOT NULL,
PARTNERSHIP_VALID BOOLEAN);

INSERT INTO SUPPLIER (NAME, EMAIL, PARTNERSHIP_VALID) VALUES ('Bershka', 'bershka@mail.com', 1);
INSERT INTO SUPPLIER (NAME, EMAIL, PARTNERSHIP_VALID) VALUES ('Zara', 'zara@mail.com', 1);
INSERT INTO SUPPLIER (NAME, EMAIL, PARTNERSHIP_VALID) VALUES ('Pull&Bear', 'pb@mail.com', 0);
INSERT INTO SUPPLIER (NAME, EMAIL, PARTNERSHIP_VALID) VALUES ('H&M', 'hm@mail.com', 1);
INSERT INTO SUPPLIER (NAME, EMAIL, PARTNERSHIP_VALID) VALUES ('4F', '4f@mail.com', 1);
CREATE SEQUENCE SUPPLIER_SEQ start with (select count(*) FROM SUPPLIER) + 1 increment by 1 minvalue 0 maxvalue 1000 nocycle;

CREATE TABLE MATERIAL (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
NAME NVARCHAR2(100) NOT NULL,
DESCRIPTION NVARCHAR2(250)
);

INSERT INTO MATERIAL (NAME, DESCRIPTION) VALUES ('Cotton', 'Cotton fibers are natural hollow fibers; they are soft, cool, known as breathable fibers and absorbent. For washing, the use of cold water is recommended.');
INSERT INTO MATERIAL (NAME, DESCRIPTION) VALUES ('Flax linen', 'Linen comes from the cellulose-based fibers of the flax plant that are hypoallergenic, moisture-resistant and breathable. ');
INSERT INTO MATERIAL (NAME, DESCRIPTION) VALUES ('Gold', 'Resistant to attack by air, heat, moisture and most solvents.');
INSERT INTO MATERIAL (NAME, DESCRIPTION) VALUES ('Silver', 'Resistant to attack by air, heat, moisture and most solvents.');
CREATE SEQUENCE MATERIAL_SEQ start with (select count(*) FROM MATERIAL) + 1 increment by 1 minvalue 0 maxvalue 1000 nocycle;

CREATE TABLE CLOTHING (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TYPE NVARCHAR2(50),
NAME NVARCHAR2(100),
PRICE NUMERIC NOT NULL,
MATERIAL_ID NUMERIC NOT NULL,
DISCOUNT NUMERIC,
COLOR NVARCHAR2(100),
STOCK NUMERIC NOT NULL,
EU_SIZE NVARCHAR2(5) NOT NULL,
SUPPLIER_ID NUMERIC NOT NULL
);

INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T', 1.99, 1, null, 'Black', 23, 'M', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T2', 2.99, 4, null, 'Black', 1, 'M', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T2', 2.99, 4, null, 'Black', 1, 'XS', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T2', 2.99, 2, null, 'Black', 0, 'S', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T2', 2.99, 2, null, 'Black', 2, 'L', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T2', 2.99, 1, null, 'Black', 0, 'M', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('T-shirt', 'Crop T3', 3.99, 1, null, 'Black', 4, 'M', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('Jeans', 'Mom jeans', 17.99, 3, null, 'Black', 0, 'M', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('Jeans', 'Mom jeans', 19.99, 2, null, 'Black', 1, 'S', 1);
INSERT INTO CLOTHING (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, COLOR, STOCK, EU_SIZE, SUPPLIER_ID) VALUES ('Jeans', 'Crop J', 51.99, 1, 20, 'Black', 23, 'M', 1);
CREATE SEQUENCE CLOTHING_SEQ start with (select count(*) FROM CLOTHING) + 1  increment by 1 minvalue 0 maxvalue 1000 nocycle;

CREATE TABLE ACCESSORY (
ID INTEGER PRIMARY KEY AUTO_INCREMENT,
TYPE NVARCHAR2(50),
NAME NVARCHAR2(100),
PRICE NUMERIC NOT NULL,
MATERIAL_ID NUMERIC NOT NULL,
DISCOUNT NUMERIC,
STOCK NUMERIC NOT NULL,
SUPPLIER_ID NUMERIC NOT NULL
);

INSERT INTO ACCESSORY (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, STOCK, SUPPLIER_ID) VALUES ('Ring', 'Lord''s', 111.99, 3, 10, 23, 3);
INSERT INTO ACCESSORY (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, STOCK, SUPPLIER_ID) VALUES ('Ring', 'Emerald', 61.99, 4, 10, 23, 3);
INSERT INTO ACCESSORY (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, STOCK, SUPPLIER_ID) VALUES ('Earrings', 'Lord''s', 71.99, 4, 10, 23, 3);
INSERT INTO ACCESSORY (TYPE, NAME, PRICE, MATERIAL_ID, DISCOUNT, STOCK, SUPPLIER_ID) VALUES ('Earrings', 'Emerald', 91.99, 4, 10, 23, 3);
CREATE SEQUENCE ACCESSORY_SEQ start with (select count(*) FROM ACCESSORY) + 1  increment by 1 minvalue 0 maxvalue 1000 nocycle;